baseURL = 'https://www.drivewingrow.com'
languageCode = 'en-us'
title = 'Drive Win Grow'
theme = 'cleanpillow'
summarylength = 10
postsPerRow = 4

googleAnalytics = 'G-K4YTZKYRKY'

[markup]
[markup.goldmark.renderer]
unsafe = true

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min='0.116.0'
